[package]
name = "keal_eframe"
version = "0.7.2"
edition = "2024"

[dependencies]
keal = { path = "../keal" }
fork = "0.1.22"
nucleo-matcher = "0.2.0"
anyhow = "1.0.86"
indexmap = "2.5.0"
smallvec = "1.13.2"
eframe = "0.32.1"
