[package]
name = "keal"
version = "0.7.2"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bitflags = "2.4.1"
serde = { version = "1.0.193", features = ["serde_derive"] }
serde_cbor = "0.11.2"
walkdir = "2.4.0"
indexmap = "2.1.0"
nucleo-matcher = "0.2.0"
