[package]
name = "keal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_dispatch = "0.3.12"
fuzzy-matcher = "0.3.7"
iced = "0.10.0"
lazy_static = "1.4.0"
tini = "1.3.0"
walkdir = "2.4.0"
