[package]
name = "keal"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.1"
enum_dispatch = "0.3.12"
fork = "0.1.22"
fuzzy-matcher = "0.3.7"
iced = { version = "0.10.0", features = ["image", "svg", "web-colors"] }
lazy_static = "1.4.0"
tini = "1.3.0"
walkdir = "2.4.0"
